# ============================== Filebeat inputs ===============================

filebeat.inputs:

  - type: filestream
    # Unique ID among all inputs, an ID is required.
    id: { { component } }

    # Change to true to enable this input configuration.
    enabled: true

    # Paths that should be crawled and fetched. Glob based paths.
    paths:
      - { { log_file } }
    fields:
       component: {{ component }}
      # - c:\programdata\elasticsearch\logs\*
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false


setup.template.settings:
  index.number_of_shards: 1

setup.kibana:



# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["172.31.31.4:5044"]


# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~


